import React from 'react';
import { Send, ExternalLink, Sparkles } from 'lucide-react';

export const OutputEditor = ({ 
  output, 
  setOutput, 
  onEvaluate, 
  recommendedToolUrl, 
  recommendedToolName, 
  isEvaluating 
}) => {
  const wordCount = output.trim() ? output.trim().split(/\s+/).length : 0;

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-7 shadow-xs space-y-6">
      
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-200">
        <div>
          <span className="bg-gov-100 text-gov-800 text-[11px] font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wider">
            Step 5: External Tool Output
          </span>
          <h3 className="text-lg font-bold text-slate-900 mt-1">
            Paste Generated AI Output
          </h3>
          <p className="text-xs text-slate-600 mt-0.5">
            Run your prompt in {recommendedToolName || 'the AI tool'} and paste the generated response below.
          </p>
        </div>

        {recommendedToolUrl && (
          <a
            href={recommendedToolUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center space-x-2 bg-slate-900 hover:bg-slate-800 text-white px-4 py-2 rounded-xl text-xs font-bold transition-all shadow-xs shrink-0 self-start sm:self-auto"
          >
            <span>Open {recommendedToolName || 'AI Tool'}</span>
            <ExternalLink className="w-3.5 h-3.5 text-slate-300" />
          </a>
        )}
      </div>

      <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-700 space-y-1.5">
        <h4 className="font-bold text-slate-900 flex items-center space-x-1.5">
          <Sparkles className="w-3.5 h-3.5 text-gov-600" />
          <span>Execution Checklist:</span>
        </h4>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-1 text-[11px]">
          <div className="p-2 bg-white rounded border border-slate-200">
            1. Copy practice material & prompt
          </div>
          <div className="p-2 bg-white rounded border border-slate-200">
            2. Run in actual AI tool
          </div>
          <div className="p-2 bg-white rounded border border-slate-200">
            3. Paste response here & evaluate
          </div>
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex justify-between items-center text-xs text-slate-500 font-medium px-1">
          <label htmlFor="output-input" className="font-semibold text-slate-700">
            Paste AI Output Here:
          </label>
          <span>{wordCount} words</span>
        </div>
        <textarea
          id="output-input"
          value={output}
          onChange={(e) => setOutput(e.target.value)}
          rows={9}
          placeholder="Paste the output generated by the AI tool here..."
          className="w-full p-4 text-xs font-mono sm:text-sm bg-slate-50 border border-slate-300 rounded-xl focus:bg-white focus:ring-2 focus:ring-gov-500 focus:border-gov-500 transition-all outline-none leading-relaxed"
        />
      </div>

      <div className="flex justify-end pt-2">
        <button
          onClick={onEvaluate}
          disabled={!output.trim() || isEvaluating}
          className={`flex items-center space-x-2 px-7 py-3 rounded-xl text-sm font-bold text-white shadow-md transition-all ${
            output.trim() && !isEvaluating
              ? 'bg-gov-600 hover:bg-gov-700 hover:shadow-lg scale-100 active:scale-95'
              : 'bg-slate-300 cursor-not-allowed opacity-70'
          }`}
        >
          {isEvaluating ? (
            <span>Evaluating Submission...</span>
          ) : (
            <>
              <span>Evaluate My Submission & Compare</span>
              <Send className="w-4 h-4" />
            </>
          )}
        </button>
      </div>

    </div>
  );
};
